media-user-token: "AtukUX7kIJiCcTfRPF9d/nDR9Fg1i2bDVm/zUDclImtykomUiyanBN5s6TFvVrMxVqIt2Pftod/uSk2EFLyJaFcUotOXD7QY4NXzva/m98qwtgMuFfZjoiVbWkcG8uuzH4NT2KQsFTCdxRnVKiUWDtuXNF3f01kRMRHl7/05AoNR4t0fLzFH7f0ar1HCkx9pTBpXotIglgerXbqFPc88g7mS25Qj2g8kMsb13llX24xjG978FA==" #If you need to obtain lyrics and aac-lc, need to change it
authorization-token: "your-authorization-token" #You don't need to change it; it can automatically obtain token
language: "zh-Hans-CN"         #supportedLanguage by each storefront --> https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
lrc-type: "syllable-lyrics"   #lyrics or syllable-lyrics
lrc-format: "lrc"   #lrc or ttml
embed-lrc: true
save-lrc-file: true
save-artist-cover: false
save-animated-artwork: false    # If enabled, requires ffmpeg
emby-animated-artwork: false    # If enabled, requires ffmpeg
embed-cover: true
cover-size: 5000x5000
cover-format: jpg       #jpg png or original
alac-save-folder: AM-DL downloads
atmos-save-folder: AM-DL-Atmos downloads
aac-save-folder: AM-DL-AAC downloads
max-memory-limit: 256 # MB
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
#set 'all' to retrieve all m3u8, and set 'hires' to only detect hires m3u8.
get-m3u8-mode: hires # all hires
aac-type: aac-lc # aac-lc aac aac-binaural aac-downmix
alac-max: 192000  #192000 96000 48000 44100
atmos-max: 2768  #2768 2448
limit-max: 200
#{AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality} {Codec} {Tag} {RecordLabel}
#example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright}){Codec}
album-folder-format: "{AlbumName}{Tag}"
#{PlaylistId} {PlaylistName} {ArtistName} {Quality} {Codec} {Tag}
playlist-folder-format: "{PlaylistName}"
#{SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality} {Codec} {Tag}
#example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]{{Tag}}"
song-file-format: "{SongNumer}. {SongName}{Tag}"
#{ArtistId} {ArtistName}/{UrlArtistName}
#if artist-folder-format set "",will not make artist folder
artist-folder-format: "{UrlArtistName}"
#if set "" will not add tag
explicit-choice : "[E]"
clean-choice : "[C]"
apple-master-choice : ""
#if set true,for playlst,will use songinfo for meta #albumname track disk
use-songinfo-for-playlist: true
#if set true,will download album cover for playlist
dl-albumcover-for-playlist: false
mv-audio-type: atmos  #atmos ac3 aac
mv-max: 2160
# storefront will be used only in searching. 
# storefront is the 2-letter country code that are available in the urls (jp, ca, us etc.).
# if your account is from Japan, you must use jp.
# if the storefront is different from your account, you will see a "failed to get lyrics" error in most of the songs. By default the storefront is set to US if not set.
storefront: "enter your account storefront"
